service: music-library

frameworkVersion: '2'

provider:
  name: 'aws'
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.appName}

custom:
  appName: ${opt:stage, 'dev'}-music-library
  
resources:
  Resources:
    database:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: partitionKey
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
        KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.appName}

functions:
  createArtist:
    name: ${self:custom.appName}-create-artist
    handler: create-artist/index.run
    events:
      - httpApi:
          path: /artist
          method: post
    environment:
      TABLE_NAME: ${self:custom.appName}
